#include <signal.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// sig_atomic_t is the appopriate type to use for
// communication from within signal handlers
static volatile sig_atomic_t time = 0;
static volatile sig_atomic_t is_paused = 0;
static volatile sig_atomic_t got_exit_signal = 0;

// initial shape generated by LLM
static void write_num(sig_atomic_t num) {
    char buf[11];
    size_t len = sizeof(buf);
    char *ptr = buf + len - sizeof(char);

    *ptr = '\n';

    // digits are written backwards,
    // so that the buffer can be written with
    // a single `write()` syscall
    do {
        char ch = '0' + (num % 10);
        num /= 10;
        ptr -= sizeof(char);
        *ptr = ch;
    } while (num);

    write(STDOUT_FILENO, ptr, buf + len - ptr);
}

void handler_toggle(int sig) {
    (void)sig;

    is_paused = !is_paused;

    // we use known-size arrays because
    // `strlen` is not allowed in signal handlers
    //
    // XXX: ...so maybe writing should be done in `main()`,
    // and the handler should just set the appropriate flags.
    if (is_paused) {
        static const char msg[] = "paused\n";
        write(STDOUT_FILENO, msg, sizeof(msg) - 1);
    } else {
        static const char msg[] = "unpaused\n";
        write(STDOUT_FILENO, msg, sizeof(msg) - 1);
    }
}

void handler_print(int sig) {
    (void)sig;
    write_num(time);
}

void handler_reset(int sig) {
    (void)sig;
    time = 0;
    static const char msg[] = "timer reset\n";
    write(STDOUT_FILENO, msg, sizeof(msg) - 1);
}

void handler_exit(int sig) {
    (void)sig;
    got_exit_signal = true;
}

void set_handler(int sig, void (*handler)(int)) {
    struct sigaction sa = {0};

    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;
    sa.sa_handler = handler;

    if (sigaction(sig, &sa, NULL) == -1) {
        perror("failed to set sigaction");
        exit(EXIT_FAILURE);
    }
}

int main(void) {
    set_handler(SIGUSR1, handler_toggle);
    set_handler(SIGUSR2, handler_print);
    set_handler(SIGINT, handler_reset);
    set_handler(SIGTERM, handler_exit);

    printf("starting main program loop...\n");

    // XXX: measuring time with a loop like this is incorrect,
    // especially because `sleep()` can be
    // interrupted by signals.
    // we should use something like `clock_gettime()` instead.
    while (!got_exit_signal) {
        if (!is_paused) {
            time += 1;
        }
        sleep(1);
    }

    printf("terminated. program time is now %d", (int)time);
    return EXIT_SUCCESS;
}
